-- DropForeignKey
ALTER TABLE "Bid" DROP CONSTRAINT "Bid_itemId_fkey";

-- AlterTable
ALTER TABLE "Bid" ADD COLUMN     "userId" INTEGER;

-- AddForeignKey
ALTER TABLE "Bid" ADD CONSTRAINT "Bid_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "Item"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Bid" ADD CONSTRAINT "Bid_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
